/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedErpRouteImport } from './routes/_authenticated/erp'
import { Route as AuthenticatedErpIndexRouteImport } from './routes/_authenticated/erp.index'
import { Route as AuthenticatedErpSuppliersRouteImport } from './routes/_authenticated/erp.suppliers'
import { Route as AuthenticatedErpSettingsRouteImport } from './routes/_authenticated/erp.settings'
import { Route as AuthenticatedErpOrdersRouteImport } from './routes/_authenticated/erp.orders'
import { Route as AuthenticatedErpMarketingRouteImport } from './routes/_authenticated/erp.marketing'
import { Route as AuthenticatedErpInventoryRouteImport } from './routes/_authenticated/erp.inventory'
import { Route as AuthenticatedErpFinanceRouteImport } from './routes/_authenticated/erp.finance'
import { Route as AuthenticatedErpCourierRouteImport } from './routes/_authenticated/erp.courier'
import { Route as AuthenticatedErpOrdersIndexRouteImport } from './routes/_authenticated/erp.orders.index'
import { Route as AuthenticatedErpFinanceIndexRouteImport } from './routes/_authenticated/erp.finance.index'
import { Route as ApiPublicWebhookPathaoRouteImport } from './routes/api/public/webhook.pathao'
import { Route as ApiPublicMktTrackerDotjsRouteImport } from './routes/api/public/mkt.tracker[.]js'
import { Route as ApiPublicMktTrackRouteImport } from './routes/api/public/mkt.track'
import { Route as ApiPublicCronSyncMarketingRouteImport } from './routes/api/public/cron.sync-marketing'
import { Route as ApiPublicCronSyncCourierRouteImport } from './routes/api/public/cron.sync-courier'
import { Route as ApiPublicCronRunRecurringRouteImport } from './routes/api/public/cron.run-recurring'
import { Route as ApiPublicCronMarketingRebuildRouteImport } from './routes/api/public/cron.marketing-rebuild'
import { Route as AuthenticatedErpOrdersWebRouteImport } from './routes/_authenticated/erp.orders.web'
import { Route as AuthenticatedErpOrdersNewRouteImport } from './routes/_authenticated/erp.orders.new'
import { Route as AuthenticatedErpOrdersListRouteImport } from './routes/_authenticated/erp.orders.list'
import { Route as AuthenticatedErpOrdersOrderIdRouteImport } from './routes/_authenticated/erp.orders.$orderId'
import { Route as AuthenticatedErpMarketingInstallRouteImport } from './routes/_authenticated/erp.marketing.install'
import { Route as AuthenticatedErpMarketingCampaignsRouteImport } from './routes/_authenticated/erp.marketing.campaigns'
import { Route as AuthenticatedErpMarketingAccountingRouteImport } from './routes/_authenticated/erp.marketing.accounting'
import { Route as AuthenticatedErpFinanceWalletsRouteImport } from './routes/_authenticated/erp.finance.wallets'
import { Route as AuthenticatedErpFinanceTaxesRouteImport } from './routes/_authenticated/erp.finance.taxes'
import { Route as AuthenticatedErpFinanceSimpleRouteImport } from './routes/_authenticated/erp.finance.simple'
import { Route as AuthenticatedErpFinanceSettingsRouteImport } from './routes/_authenticated/erp.finance.settings'
import { Route as AuthenticatedErpFinanceReportsRouteImport } from './routes/_authenticated/erp.finance.reports'
import { Route as AuthenticatedErpFinanceRecurringRouteImport } from './routes/_authenticated/erp.finance.recurring'
import { Route as AuthenticatedErpFinanceReconciliationRouteImport } from './routes/_authenticated/erp.finance.reconciliation'
import { Route as AuthenticatedErpFinanceReceivablesRouteImport } from './routes/_authenticated/erp.finance.receivables'
import { Route as AuthenticatedErpFinanceProductProfitabilityRouteImport } from './routes/_authenticated/erp.finance.product-profitability'
import { Route as AuthenticatedErpFinancePayablesRouteImport } from './routes/_authenticated/erp.finance.payables'
import { Route as AuthenticatedErpFinanceJournalRouteImport } from './routes/_authenticated/erp.finance.journal'
import { Route as AuthenticatedErpFinanceFxRouteImport } from './routes/_authenticated/erp.finance.fx'
import { Route as AuthenticatedErpFinanceBudgetsRouteImport } from './routes/_authenticated/erp.finance.budgets'
import { Route as AuthenticatedErpFinanceBrandProfitabilityRouteImport } from './routes/_authenticated/erp.finance.brand-profitability'
import { Route as AuthenticatedErpFinanceAuditRouteImport } from './routes/_authenticated/erp.finance.audit'
import { Route as AuthenticatedErpFinanceAccountsRouteImport } from './routes/_authenticated/erp.finance.accounts'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedErpRoute = AuthenticatedErpRouteImport.update({
  id: '/erp',
  path: '/erp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErpIndexRoute = AuthenticatedErpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedErpRoute,
} as any)
const AuthenticatedErpSuppliersRoute =
  AuthenticatedErpSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedErpRoute,
  } as any)
const AuthenticatedErpSettingsRoute =
  AuthenticatedErpSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedErpRoute,
  } as any)
const AuthenticatedErpOrdersRoute = AuthenticatedErpOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedErpRoute,
} as any)
const AuthenticatedErpMarketingRoute =
  AuthenticatedErpMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => AuthenticatedErpRoute,
  } as any)
const AuthenticatedErpInventoryRoute =
  AuthenticatedErpInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedErpRoute,
  } as any)
const AuthenticatedErpFinanceRoute = AuthenticatedErpFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedErpRoute,
} as any)
const AuthenticatedErpCourierRoute = AuthenticatedErpCourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => AuthenticatedErpRoute,
} as any)
const AuthenticatedErpOrdersIndexRoute =
  AuthenticatedErpOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedErpOrdersRoute,
  } as any)
const AuthenticatedErpFinanceIndexRoute =
  AuthenticatedErpFinanceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedErpFinanceRoute,
  } as any)
const ApiPublicWebhookPathaoRoute = ApiPublicWebhookPathaoRouteImport.update({
  id: '/api/public/webhook/pathao',
  path: '/api/public/webhook/pathao',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMktTrackerDotjsRoute =
  ApiPublicMktTrackerDotjsRouteImport.update({
    id: '/api/public/mkt/tracker.js',
    path: '/api/public/mkt/tracker.js',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMktTrackRoute = ApiPublicMktTrackRouteImport.update({
  id: '/api/public/mkt/track',
  path: '/api/public/mkt/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronSyncMarketingRoute =
  ApiPublicCronSyncMarketingRouteImport.update({
    id: '/api/public/cron/sync-marketing',
    path: '/api/public/cron/sync-marketing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSyncCourierRoute =
  ApiPublicCronSyncCourierRouteImport.update({
    id: '/api/public/cron/sync-courier',
    path: '/api/public/cron/sync-courier',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronRunRecurringRoute =
  ApiPublicCronRunRecurringRouteImport.update({
    id: '/api/public/cron/run-recurring',
    path: '/api/public/cron/run-recurring',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronMarketingRebuildRoute =
  ApiPublicCronMarketingRebuildRouteImport.update({
    id: '/api/public/cron/marketing-rebuild',
    path: '/api/public/cron/marketing-rebuild',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedErpOrdersWebRoute =
  AuthenticatedErpOrdersWebRouteImport.update({
    id: '/web',
    path: '/web',
    getParentRoute: () => AuthenticatedErpOrdersRoute,
  } as any)
const AuthenticatedErpOrdersNewRoute =
  AuthenticatedErpOrdersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedErpOrdersRoute,
  } as any)
const AuthenticatedErpOrdersListRoute =
  AuthenticatedErpOrdersListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => AuthenticatedErpOrdersRoute,
  } as any)
const AuthenticatedErpOrdersOrderIdRoute =
  AuthenticatedErpOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedErpOrdersRoute,
  } as any)
const AuthenticatedErpMarketingInstallRoute =
  AuthenticatedErpMarketingInstallRouteImport.update({
    id: '/install',
    path: '/install',
    getParentRoute: () => AuthenticatedErpMarketingRoute,
  } as any)
const AuthenticatedErpMarketingCampaignsRoute =
  AuthenticatedErpMarketingCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedErpMarketingRoute,
  } as any)
const AuthenticatedErpMarketingAccountingRoute =
  AuthenticatedErpMarketingAccountingRouteImport.update({
    id: '/accounting',
    path: '/accounting',
    getParentRoute: () => AuthenticatedErpMarketingRoute,
  } as any)
const AuthenticatedErpFinanceWalletsRoute =
  AuthenticatedErpFinanceWalletsRouteImport.update({
    id: '/wallets',
    path: '/wallets',
    getParentRoute: () => AuthenticatedErpFinanceRoute,
  } as any)
const AuthenticatedErpFinanceTaxesRoute =
  AuthenticatedErpFinanceTaxesRouteImport.update({
    id: '/taxes',
    path: '/taxes',
    getParentRoute: () => AuthenticatedErpFinanceRoute,
  } as any)
const AuthenticatedErpFinanceSimpleRoute =
  AuthenticatedErpFinanceSimpleRouteImport.update({
    id: '/simple',
    path: '/simple',
    getParentRoute: () => AuthenticatedErpFinanceRoute,
  } as any)
const AuthenticatedErpFinanceSettingsRoute =
  AuthenticatedErpFinanceSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedErpFinanceRoute,
  } as any)
const AuthenticatedErpFinanceReportsRoute =
  AuthenticatedErpFinanceReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedErpFinanceRoute,
  } as any)
const AuthenticatedErpFinanceRecurringRoute =
  AuthenticatedErpFinanceRecurringRouteImport.update({
    id: '/recurring',
    path: '/recurring',
    getParentRoute: () => AuthenticatedErpFinanceRoute,
  } as any)
const AuthenticatedErpFinanceReconciliationRoute =
  AuthenticatedErpFinanceReconciliationRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => AuthenticatedErpFinanceRoute,
  } as any)
const AuthenticatedErpFinanceReceivablesRoute =
  AuthenticatedErpFinanceReceivablesRouteImport.update({
    id: '/receivables',
    path: '/receivables',
    getParentRoute: () => AuthenticatedErpFinanceRoute,
  } as any)
const AuthenticatedErpFinanceProductProfitabilityRoute =
  AuthenticatedErpFinanceProductProfitabilityRouteImport.update({
    id: '/product-profitability',
    path: '/product-profitability',
    getParentRoute: () => AuthenticatedErpFinanceRoute,
  } as any)
const AuthenticatedErpFinancePayablesRoute =
  AuthenticatedErpFinancePayablesRouteImport.update({
    id: '/payables',
    path: '/payables',
    getParentRoute: () => AuthenticatedErpFinanceRoute,
  } as any)
const AuthenticatedErpFinanceJournalRoute =
  AuthenticatedErpFinanceJournalRouteImport.update({
    id: '/journal',
    path: '/journal',
    getParentRoute: () => AuthenticatedErpFinanceRoute,
  } as any)
const AuthenticatedErpFinanceFxRoute =
  AuthenticatedErpFinanceFxRouteImport.update({
    id: '/fx',
    path: '/fx',
    getParentRoute: () => AuthenticatedErpFinanceRoute,
  } as any)
const AuthenticatedErpFinanceBudgetsRoute =
  AuthenticatedErpFinanceBudgetsRouteImport.update({
    id: '/budgets',
    path: '/budgets',
    getParentRoute: () => AuthenticatedErpFinanceRoute,
  } as any)
const AuthenticatedErpFinanceBrandProfitabilityRoute =
  AuthenticatedErpFinanceBrandProfitabilityRouteImport.update({
    id: '/brand-profitability',
    path: '/brand-profitability',
    getParentRoute: () => AuthenticatedErpFinanceRoute,
  } as any)
const AuthenticatedErpFinanceAuditRoute =
  AuthenticatedErpFinanceAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedErpFinanceRoute,
  } as any)
const AuthenticatedErpFinanceAccountsRoute =
  AuthenticatedErpFinanceAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedErpFinanceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/erp': typeof AuthenticatedErpRouteWithChildren
  '/erp/courier': typeof AuthenticatedErpCourierRoute
  '/erp/finance': typeof AuthenticatedErpFinanceRouteWithChildren
  '/erp/inventory': typeof AuthenticatedErpInventoryRoute
  '/erp/marketing': typeof AuthenticatedErpMarketingRouteWithChildren
  '/erp/orders': typeof AuthenticatedErpOrdersRouteWithChildren
  '/erp/settings': typeof AuthenticatedErpSettingsRoute
  '/erp/suppliers': typeof AuthenticatedErpSuppliersRoute
  '/erp/': typeof AuthenticatedErpIndexRoute
  '/erp/finance/accounts': typeof AuthenticatedErpFinanceAccountsRoute
  '/erp/finance/audit': typeof AuthenticatedErpFinanceAuditRoute
  '/erp/finance/brand-profitability': typeof AuthenticatedErpFinanceBrandProfitabilityRoute
  '/erp/finance/budgets': typeof AuthenticatedErpFinanceBudgetsRoute
  '/erp/finance/fx': typeof AuthenticatedErpFinanceFxRoute
  '/erp/finance/journal': typeof AuthenticatedErpFinanceJournalRoute
  '/erp/finance/payables': typeof AuthenticatedErpFinancePayablesRoute
  '/erp/finance/product-profitability': typeof AuthenticatedErpFinanceProductProfitabilityRoute
  '/erp/finance/receivables': typeof AuthenticatedErpFinanceReceivablesRoute
  '/erp/finance/reconciliation': typeof AuthenticatedErpFinanceReconciliationRoute
  '/erp/finance/recurring': typeof AuthenticatedErpFinanceRecurringRoute
  '/erp/finance/reports': typeof AuthenticatedErpFinanceReportsRoute
  '/erp/finance/settings': typeof AuthenticatedErpFinanceSettingsRoute
  '/erp/finance/simple': typeof AuthenticatedErpFinanceSimpleRoute
  '/erp/finance/taxes': typeof AuthenticatedErpFinanceTaxesRoute
  '/erp/finance/wallets': typeof AuthenticatedErpFinanceWalletsRoute
  '/erp/marketing/accounting': typeof AuthenticatedErpMarketingAccountingRoute
  '/erp/marketing/campaigns': typeof AuthenticatedErpMarketingCampaignsRoute
  '/erp/marketing/install': typeof AuthenticatedErpMarketingInstallRoute
  '/erp/orders/$orderId': typeof AuthenticatedErpOrdersOrderIdRoute
  '/erp/orders/list': typeof AuthenticatedErpOrdersListRoute
  '/erp/orders/new': typeof AuthenticatedErpOrdersNewRoute
  '/erp/orders/web': typeof AuthenticatedErpOrdersWebRoute
  '/api/public/cron/marketing-rebuild': typeof ApiPublicCronMarketingRebuildRoute
  '/api/public/cron/run-recurring': typeof ApiPublicCronRunRecurringRoute
  '/api/public/cron/sync-courier': typeof ApiPublicCronSyncCourierRoute
  '/api/public/cron/sync-marketing': typeof ApiPublicCronSyncMarketingRoute
  '/api/public/mkt/track': typeof ApiPublicMktTrackRoute
  '/api/public/mkt/tracker.js': typeof ApiPublicMktTrackerDotjsRoute
  '/api/public/webhook/pathao': typeof ApiPublicWebhookPathaoRoute
  '/erp/finance/': typeof AuthenticatedErpFinanceIndexRoute
  '/erp/orders/': typeof AuthenticatedErpOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/erp/courier': typeof AuthenticatedErpCourierRoute
  '/erp/inventory': typeof AuthenticatedErpInventoryRoute
  '/erp/marketing': typeof AuthenticatedErpMarketingRouteWithChildren
  '/erp/settings': typeof AuthenticatedErpSettingsRoute
  '/erp/suppliers': typeof AuthenticatedErpSuppliersRoute
  '/erp': typeof AuthenticatedErpIndexRoute
  '/erp/finance/accounts': typeof AuthenticatedErpFinanceAccountsRoute
  '/erp/finance/audit': typeof AuthenticatedErpFinanceAuditRoute
  '/erp/finance/brand-profitability': typeof AuthenticatedErpFinanceBrandProfitabilityRoute
  '/erp/finance/budgets': typeof AuthenticatedErpFinanceBudgetsRoute
  '/erp/finance/fx': typeof AuthenticatedErpFinanceFxRoute
  '/erp/finance/journal': typeof AuthenticatedErpFinanceJournalRoute
  '/erp/finance/payables': typeof AuthenticatedErpFinancePayablesRoute
  '/erp/finance/product-profitability': typeof AuthenticatedErpFinanceProductProfitabilityRoute
  '/erp/finance/receivables': typeof AuthenticatedErpFinanceReceivablesRoute
  '/erp/finance/reconciliation': typeof AuthenticatedErpFinanceReconciliationRoute
  '/erp/finance/recurring': typeof AuthenticatedErpFinanceRecurringRoute
  '/erp/finance/reports': typeof AuthenticatedErpFinanceReportsRoute
  '/erp/finance/settings': typeof AuthenticatedErpFinanceSettingsRoute
  '/erp/finance/simple': typeof AuthenticatedErpFinanceSimpleRoute
  '/erp/finance/taxes': typeof AuthenticatedErpFinanceTaxesRoute
  '/erp/finance/wallets': typeof AuthenticatedErpFinanceWalletsRoute
  '/erp/marketing/accounting': typeof AuthenticatedErpMarketingAccountingRoute
  '/erp/marketing/campaigns': typeof AuthenticatedErpMarketingCampaignsRoute
  '/erp/marketing/install': typeof AuthenticatedErpMarketingInstallRoute
  '/erp/orders/$orderId': typeof AuthenticatedErpOrdersOrderIdRoute
  '/erp/orders/list': typeof AuthenticatedErpOrdersListRoute
  '/erp/orders/new': typeof AuthenticatedErpOrdersNewRoute
  '/erp/orders/web': typeof AuthenticatedErpOrdersWebRoute
  '/api/public/cron/marketing-rebuild': typeof ApiPublicCronMarketingRebuildRoute
  '/api/public/cron/run-recurring': typeof ApiPublicCronRunRecurringRoute
  '/api/public/cron/sync-courier': typeof ApiPublicCronSyncCourierRoute
  '/api/public/cron/sync-marketing': typeof ApiPublicCronSyncMarketingRoute
  '/api/public/mkt/track': typeof ApiPublicMktTrackRoute
  '/api/public/mkt/tracker.js': typeof ApiPublicMktTrackerDotjsRoute
  '/api/public/webhook/pathao': typeof ApiPublicWebhookPathaoRoute
  '/erp/finance': typeof AuthenticatedErpFinanceIndexRoute
  '/erp/orders': typeof AuthenticatedErpOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/erp': typeof AuthenticatedErpRouteWithChildren
  '/_authenticated/erp/courier': typeof AuthenticatedErpCourierRoute
  '/_authenticated/erp/finance': typeof AuthenticatedErpFinanceRouteWithChildren
  '/_authenticated/erp/inventory': typeof AuthenticatedErpInventoryRoute
  '/_authenticated/erp/marketing': typeof AuthenticatedErpMarketingRouteWithChildren
  '/_authenticated/erp/orders': typeof AuthenticatedErpOrdersRouteWithChildren
  '/_authenticated/erp/settings': typeof AuthenticatedErpSettingsRoute
  '/_authenticated/erp/suppliers': typeof AuthenticatedErpSuppliersRoute
  '/_authenticated/erp/': typeof AuthenticatedErpIndexRoute
  '/_authenticated/erp/finance/accounts': typeof AuthenticatedErpFinanceAccountsRoute
  '/_authenticated/erp/finance/audit': typeof AuthenticatedErpFinanceAuditRoute
  '/_authenticated/erp/finance/brand-profitability': typeof AuthenticatedErpFinanceBrandProfitabilityRoute
  '/_authenticated/erp/finance/budgets': typeof AuthenticatedErpFinanceBudgetsRoute
  '/_authenticated/erp/finance/fx': typeof AuthenticatedErpFinanceFxRoute
  '/_authenticated/erp/finance/journal': typeof AuthenticatedErpFinanceJournalRoute
  '/_authenticated/erp/finance/payables': typeof AuthenticatedErpFinancePayablesRoute
  '/_authenticated/erp/finance/product-profitability': typeof AuthenticatedErpFinanceProductProfitabilityRoute
  '/_authenticated/erp/finance/receivables': typeof AuthenticatedErpFinanceReceivablesRoute
  '/_authenticated/erp/finance/reconciliation': typeof AuthenticatedErpFinanceReconciliationRoute
  '/_authenticated/erp/finance/recurring': typeof AuthenticatedErpFinanceRecurringRoute
  '/_authenticated/erp/finance/reports': typeof AuthenticatedErpFinanceReportsRoute
  '/_authenticated/erp/finance/settings': typeof AuthenticatedErpFinanceSettingsRoute
  '/_authenticated/erp/finance/simple': typeof AuthenticatedErpFinanceSimpleRoute
  '/_authenticated/erp/finance/taxes': typeof AuthenticatedErpFinanceTaxesRoute
  '/_authenticated/erp/finance/wallets': typeof AuthenticatedErpFinanceWalletsRoute
  '/_authenticated/erp/marketing/accounting': typeof AuthenticatedErpMarketingAccountingRoute
  '/_authenticated/erp/marketing/campaigns': typeof AuthenticatedErpMarketingCampaignsRoute
  '/_authenticated/erp/marketing/install': typeof AuthenticatedErpMarketingInstallRoute
  '/_authenticated/erp/orders/$orderId': typeof AuthenticatedErpOrdersOrderIdRoute
  '/_authenticated/erp/orders/list': typeof AuthenticatedErpOrdersListRoute
  '/_authenticated/erp/orders/new': typeof AuthenticatedErpOrdersNewRoute
  '/_authenticated/erp/orders/web': typeof AuthenticatedErpOrdersWebRoute
  '/api/public/cron/marketing-rebuild': typeof ApiPublicCronMarketingRebuildRoute
  '/api/public/cron/run-recurring': typeof ApiPublicCronRunRecurringRoute
  '/api/public/cron/sync-courier': typeof ApiPublicCronSyncCourierRoute
  '/api/public/cron/sync-marketing': typeof ApiPublicCronSyncMarketingRoute
  '/api/public/mkt/track': typeof ApiPublicMktTrackRoute
  '/api/public/mkt/tracker.js': typeof ApiPublicMktTrackerDotjsRoute
  '/api/public/webhook/pathao': typeof ApiPublicWebhookPathaoRoute
  '/_authenticated/erp/finance/': typeof AuthenticatedErpFinanceIndexRoute
  '/_authenticated/erp/orders/': typeof AuthenticatedErpOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/erp'
    | '/erp/courier'
    | '/erp/finance'
    | '/erp/inventory'
    | '/erp/marketing'
    | '/erp/orders'
    | '/erp/settings'
    | '/erp/suppliers'
    | '/erp/'
    | '/erp/finance/accounts'
    | '/erp/finance/audit'
    | '/erp/finance/brand-profitability'
    | '/erp/finance/budgets'
    | '/erp/finance/fx'
    | '/erp/finance/journal'
    | '/erp/finance/payables'
    | '/erp/finance/product-profitability'
    | '/erp/finance/receivables'
    | '/erp/finance/reconciliation'
    | '/erp/finance/recurring'
    | '/erp/finance/reports'
    | '/erp/finance/settings'
    | '/erp/finance/simple'
    | '/erp/finance/taxes'
    | '/erp/finance/wallets'
    | '/erp/marketing/accounting'
    | '/erp/marketing/campaigns'
    | '/erp/marketing/install'
    | '/erp/orders/$orderId'
    | '/erp/orders/list'
    | '/erp/orders/new'
    | '/erp/orders/web'
    | '/api/public/cron/marketing-rebuild'
    | '/api/public/cron/run-recurring'
    | '/api/public/cron/sync-courier'
    | '/api/public/cron/sync-marketing'
    | '/api/public/mkt/track'
    | '/api/public/mkt/tracker.js'
    | '/api/public/webhook/pathao'
    | '/erp/finance/'
    | '/erp/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/erp/courier'
    | '/erp/inventory'
    | '/erp/marketing'
    | '/erp/settings'
    | '/erp/suppliers'
    | '/erp'
    | '/erp/finance/accounts'
    | '/erp/finance/audit'
    | '/erp/finance/brand-profitability'
    | '/erp/finance/budgets'
    | '/erp/finance/fx'
    | '/erp/finance/journal'
    | '/erp/finance/payables'
    | '/erp/finance/product-profitability'
    | '/erp/finance/receivables'
    | '/erp/finance/reconciliation'
    | '/erp/finance/recurring'
    | '/erp/finance/reports'
    | '/erp/finance/settings'
    | '/erp/finance/simple'
    | '/erp/finance/taxes'
    | '/erp/finance/wallets'
    | '/erp/marketing/accounting'
    | '/erp/marketing/campaigns'
    | '/erp/marketing/install'
    | '/erp/orders/$orderId'
    | '/erp/orders/list'
    | '/erp/orders/new'
    | '/erp/orders/web'
    | '/api/public/cron/marketing-rebuild'
    | '/api/public/cron/run-recurring'
    | '/api/public/cron/sync-courier'
    | '/api/public/cron/sync-marketing'
    | '/api/public/mkt/track'
    | '/api/public/mkt/tracker.js'
    | '/api/public/webhook/pathao'
    | '/erp/finance'
    | '/erp/orders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/erp'
    | '/_authenticated/erp/courier'
    | '/_authenticated/erp/finance'
    | '/_authenticated/erp/inventory'
    | '/_authenticated/erp/marketing'
    | '/_authenticated/erp/orders'
    | '/_authenticated/erp/settings'
    | '/_authenticated/erp/suppliers'
    | '/_authenticated/erp/'
    | '/_authenticated/erp/finance/accounts'
    | '/_authenticated/erp/finance/audit'
    | '/_authenticated/erp/finance/brand-profitability'
    | '/_authenticated/erp/finance/budgets'
    | '/_authenticated/erp/finance/fx'
    | '/_authenticated/erp/finance/journal'
    | '/_authenticated/erp/finance/payables'
    | '/_authenticated/erp/finance/product-profitability'
    | '/_authenticated/erp/finance/receivables'
    | '/_authenticated/erp/finance/reconciliation'
    | '/_authenticated/erp/finance/recurring'
    | '/_authenticated/erp/finance/reports'
    | '/_authenticated/erp/finance/settings'
    | '/_authenticated/erp/finance/simple'
    | '/_authenticated/erp/finance/taxes'
    | '/_authenticated/erp/finance/wallets'
    | '/_authenticated/erp/marketing/accounting'
    | '/_authenticated/erp/marketing/campaigns'
    | '/_authenticated/erp/marketing/install'
    | '/_authenticated/erp/orders/$orderId'
    | '/_authenticated/erp/orders/list'
    | '/_authenticated/erp/orders/new'
    | '/_authenticated/erp/orders/web'
    | '/api/public/cron/marketing-rebuild'
    | '/api/public/cron/run-recurring'
    | '/api/public/cron/sync-courier'
    | '/api/public/cron/sync-marketing'
    | '/api/public/mkt/track'
    | '/api/public/mkt/tracker.js'
    | '/api/public/webhook/pathao'
    | '/_authenticated/erp/finance/'
    | '/_authenticated/erp/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCronMarketingRebuildRoute: typeof ApiPublicCronMarketingRebuildRoute
  ApiPublicCronRunRecurringRoute: typeof ApiPublicCronRunRecurringRoute
  ApiPublicCronSyncCourierRoute: typeof ApiPublicCronSyncCourierRoute
  ApiPublicCronSyncMarketingRoute: typeof ApiPublicCronSyncMarketingRoute
  ApiPublicMktTrackRoute: typeof ApiPublicMktTrackRoute
  ApiPublicMktTrackerDotjsRoute: typeof ApiPublicMktTrackerDotjsRoute
  ApiPublicWebhookPathaoRoute: typeof ApiPublicWebhookPathaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/erp': {
      id: '/_authenticated/erp'
      path: '/erp'
      fullPath: '/erp'
      preLoaderRoute: typeof AuthenticatedErpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/erp/': {
      id: '/_authenticated/erp/'
      path: '/'
      fullPath: '/erp/'
      preLoaderRoute: typeof AuthenticatedErpIndexRouteImport
      parentRoute: typeof AuthenticatedErpRoute
    }
    '/_authenticated/erp/suppliers': {
      id: '/_authenticated/erp/suppliers'
      path: '/suppliers'
      fullPath: '/erp/suppliers'
      preLoaderRoute: typeof AuthenticatedErpSuppliersRouteImport
      parentRoute: typeof AuthenticatedErpRoute
    }
    '/_authenticated/erp/settings': {
      id: '/_authenticated/erp/settings'
      path: '/settings'
      fullPath: '/erp/settings'
      preLoaderRoute: typeof AuthenticatedErpSettingsRouteImport
      parentRoute: typeof AuthenticatedErpRoute
    }
    '/_authenticated/erp/orders': {
      id: '/_authenticated/erp/orders'
      path: '/orders'
      fullPath: '/erp/orders'
      preLoaderRoute: typeof AuthenticatedErpOrdersRouteImport
      parentRoute: typeof AuthenticatedErpRoute
    }
    '/_authenticated/erp/marketing': {
      id: '/_authenticated/erp/marketing'
      path: '/marketing'
      fullPath: '/erp/marketing'
      preLoaderRoute: typeof AuthenticatedErpMarketingRouteImport
      parentRoute: typeof AuthenticatedErpRoute
    }
    '/_authenticated/erp/inventory': {
      id: '/_authenticated/erp/inventory'
      path: '/inventory'
      fullPath: '/erp/inventory'
      preLoaderRoute: typeof AuthenticatedErpInventoryRouteImport
      parentRoute: typeof AuthenticatedErpRoute
    }
    '/_authenticated/erp/finance': {
      id: '/_authenticated/erp/finance'
      path: '/finance'
      fullPath: '/erp/finance'
      preLoaderRoute: typeof AuthenticatedErpFinanceRouteImport
      parentRoute: typeof AuthenticatedErpRoute
    }
    '/_authenticated/erp/courier': {
      id: '/_authenticated/erp/courier'
      path: '/courier'
      fullPath: '/erp/courier'
      preLoaderRoute: typeof AuthenticatedErpCourierRouteImport
      parentRoute: typeof AuthenticatedErpRoute
    }
    '/_authenticated/erp/orders/': {
      id: '/_authenticated/erp/orders/'
      path: '/'
      fullPath: '/erp/orders/'
      preLoaderRoute: typeof AuthenticatedErpOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedErpOrdersRoute
    }
    '/_authenticated/erp/finance/': {
      id: '/_authenticated/erp/finance/'
      path: '/'
      fullPath: '/erp/finance/'
      preLoaderRoute: typeof AuthenticatedErpFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedErpFinanceRoute
    }
    '/api/public/webhook/pathao': {
      id: '/api/public/webhook/pathao'
      path: '/api/public/webhook/pathao'
      fullPath: '/api/public/webhook/pathao'
      preLoaderRoute: typeof ApiPublicWebhookPathaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mkt/tracker.js': {
      id: '/api/public/mkt/tracker.js'
      path: '/api/public/mkt/tracker.js'
      fullPath: '/api/public/mkt/tracker.js'
      preLoaderRoute: typeof ApiPublicMktTrackerDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mkt/track': {
      id: '/api/public/mkt/track'
      path: '/api/public/mkt/track'
      fullPath: '/api/public/mkt/track'
      preLoaderRoute: typeof ApiPublicMktTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sync-marketing': {
      id: '/api/public/cron/sync-marketing'
      path: '/api/public/cron/sync-marketing'
      fullPath: '/api/public/cron/sync-marketing'
      preLoaderRoute: typeof ApiPublicCronSyncMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/sync-courier': {
      id: '/api/public/cron/sync-courier'
      path: '/api/public/cron/sync-courier'
      fullPath: '/api/public/cron/sync-courier'
      preLoaderRoute: typeof ApiPublicCronSyncCourierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/run-recurring': {
      id: '/api/public/cron/run-recurring'
      path: '/api/public/cron/run-recurring'
      fullPath: '/api/public/cron/run-recurring'
      preLoaderRoute: typeof ApiPublicCronRunRecurringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/marketing-rebuild': {
      id: '/api/public/cron/marketing-rebuild'
      path: '/api/public/cron/marketing-rebuild'
      fullPath: '/api/public/cron/marketing-rebuild'
      preLoaderRoute: typeof ApiPublicCronMarketingRebuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/erp/orders/web': {
      id: '/_authenticated/erp/orders/web'
      path: '/web'
      fullPath: '/erp/orders/web'
      preLoaderRoute: typeof AuthenticatedErpOrdersWebRouteImport
      parentRoute: typeof AuthenticatedErpOrdersRoute
    }
    '/_authenticated/erp/orders/new': {
      id: '/_authenticated/erp/orders/new'
      path: '/new'
      fullPath: '/erp/orders/new'
      preLoaderRoute: typeof AuthenticatedErpOrdersNewRouteImport
      parentRoute: typeof AuthenticatedErpOrdersRoute
    }
    '/_authenticated/erp/orders/list': {
      id: '/_authenticated/erp/orders/list'
      path: '/list'
      fullPath: '/erp/orders/list'
      preLoaderRoute: typeof AuthenticatedErpOrdersListRouteImport
      parentRoute: typeof AuthenticatedErpOrdersRoute
    }
    '/_authenticated/erp/orders/$orderId': {
      id: '/_authenticated/erp/orders/$orderId'
      path: '/$orderId'
      fullPath: '/erp/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedErpOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedErpOrdersRoute
    }
    '/_authenticated/erp/marketing/install': {
      id: '/_authenticated/erp/marketing/install'
      path: '/install'
      fullPath: '/erp/marketing/install'
      preLoaderRoute: typeof AuthenticatedErpMarketingInstallRouteImport
      parentRoute: typeof AuthenticatedErpMarketingRoute
    }
    '/_authenticated/erp/marketing/campaigns': {
      id: '/_authenticated/erp/marketing/campaigns'
      path: '/campaigns'
      fullPath: '/erp/marketing/campaigns'
      preLoaderRoute: typeof AuthenticatedErpMarketingCampaignsRouteImport
      parentRoute: typeof AuthenticatedErpMarketingRoute
    }
    '/_authenticated/erp/marketing/accounting': {
      id: '/_authenticated/erp/marketing/accounting'
      path: '/accounting'
      fullPath: '/erp/marketing/accounting'
      preLoaderRoute: typeof AuthenticatedErpMarketingAccountingRouteImport
      parentRoute: typeof AuthenticatedErpMarketingRoute
    }
    '/_authenticated/erp/finance/wallets': {
      id: '/_authenticated/erp/finance/wallets'
      path: '/wallets'
      fullPath: '/erp/finance/wallets'
      preLoaderRoute: typeof AuthenticatedErpFinanceWalletsRouteImport
      parentRoute: typeof AuthenticatedErpFinanceRoute
    }
    '/_authenticated/erp/finance/taxes': {
      id: '/_authenticated/erp/finance/taxes'
      path: '/taxes'
      fullPath: '/erp/finance/taxes'
      preLoaderRoute: typeof AuthenticatedErpFinanceTaxesRouteImport
      parentRoute: typeof AuthenticatedErpFinanceRoute
    }
    '/_authenticated/erp/finance/simple': {
      id: '/_authenticated/erp/finance/simple'
      path: '/simple'
      fullPath: '/erp/finance/simple'
      preLoaderRoute: typeof AuthenticatedErpFinanceSimpleRouteImport
      parentRoute: typeof AuthenticatedErpFinanceRoute
    }
    '/_authenticated/erp/finance/settings': {
      id: '/_authenticated/erp/finance/settings'
      path: '/settings'
      fullPath: '/erp/finance/settings'
      preLoaderRoute: typeof AuthenticatedErpFinanceSettingsRouteImport
      parentRoute: typeof AuthenticatedErpFinanceRoute
    }
    '/_authenticated/erp/finance/reports': {
      id: '/_authenticated/erp/finance/reports'
      path: '/reports'
      fullPath: '/erp/finance/reports'
      preLoaderRoute: typeof AuthenticatedErpFinanceReportsRouteImport
      parentRoute: typeof AuthenticatedErpFinanceRoute
    }
    '/_authenticated/erp/finance/recurring': {
      id: '/_authenticated/erp/finance/recurring'
      path: '/recurring'
      fullPath: '/erp/finance/recurring'
      preLoaderRoute: typeof AuthenticatedErpFinanceRecurringRouteImport
      parentRoute: typeof AuthenticatedErpFinanceRoute
    }
    '/_authenticated/erp/finance/reconciliation': {
      id: '/_authenticated/erp/finance/reconciliation'
      path: '/reconciliation'
      fullPath: '/erp/finance/reconciliation'
      preLoaderRoute: typeof AuthenticatedErpFinanceReconciliationRouteImport
      parentRoute: typeof AuthenticatedErpFinanceRoute
    }
    '/_authenticated/erp/finance/receivables': {
      id: '/_authenticated/erp/finance/receivables'
      path: '/receivables'
      fullPath: '/erp/finance/receivables'
      preLoaderRoute: typeof AuthenticatedErpFinanceReceivablesRouteImport
      parentRoute: typeof AuthenticatedErpFinanceRoute
    }
    '/_authenticated/erp/finance/product-profitability': {
      id: '/_authenticated/erp/finance/product-profitability'
      path: '/product-profitability'
      fullPath: '/erp/finance/product-profitability'
      preLoaderRoute: typeof AuthenticatedErpFinanceProductProfitabilityRouteImport
      parentRoute: typeof AuthenticatedErpFinanceRoute
    }
    '/_authenticated/erp/finance/payables': {
      id: '/_authenticated/erp/finance/payables'
      path: '/payables'
      fullPath: '/erp/finance/payables'
      preLoaderRoute: typeof AuthenticatedErpFinancePayablesRouteImport
      parentRoute: typeof AuthenticatedErpFinanceRoute
    }
    '/_authenticated/erp/finance/journal': {
      id: '/_authenticated/erp/finance/journal'
      path: '/journal'
      fullPath: '/erp/finance/journal'
      preLoaderRoute: typeof AuthenticatedErpFinanceJournalRouteImport
      parentRoute: typeof AuthenticatedErpFinanceRoute
    }
    '/_authenticated/erp/finance/fx': {
      id: '/_authenticated/erp/finance/fx'
      path: '/fx'
      fullPath: '/erp/finance/fx'
      preLoaderRoute: typeof AuthenticatedErpFinanceFxRouteImport
      parentRoute: typeof AuthenticatedErpFinanceRoute
    }
    '/_authenticated/erp/finance/budgets': {
      id: '/_authenticated/erp/finance/budgets'
      path: '/budgets'
      fullPath: '/erp/finance/budgets'
      preLoaderRoute: typeof AuthenticatedErpFinanceBudgetsRouteImport
      parentRoute: typeof AuthenticatedErpFinanceRoute
    }
    '/_authenticated/erp/finance/brand-profitability': {
      id: '/_authenticated/erp/finance/brand-profitability'
      path: '/brand-profitability'
      fullPath: '/erp/finance/brand-profitability'
      preLoaderRoute: typeof AuthenticatedErpFinanceBrandProfitabilityRouteImport
      parentRoute: typeof AuthenticatedErpFinanceRoute
    }
    '/_authenticated/erp/finance/audit': {
      id: '/_authenticated/erp/finance/audit'
      path: '/audit'
      fullPath: '/erp/finance/audit'
      preLoaderRoute: typeof AuthenticatedErpFinanceAuditRouteImport
      parentRoute: typeof AuthenticatedErpFinanceRoute
    }
    '/_authenticated/erp/finance/accounts': {
      id: '/_authenticated/erp/finance/accounts'
      path: '/accounts'
      fullPath: '/erp/finance/accounts'
      preLoaderRoute: typeof AuthenticatedErpFinanceAccountsRouteImport
      parentRoute: typeof AuthenticatedErpFinanceRoute
    }
  }
}

interface AuthenticatedErpFinanceRouteChildren {
  AuthenticatedErpFinanceAccountsRoute: typeof AuthenticatedErpFinanceAccountsRoute
  AuthenticatedErpFinanceAuditRoute: typeof AuthenticatedErpFinanceAuditRoute
  AuthenticatedErpFinanceBrandProfitabilityRoute: typeof AuthenticatedErpFinanceBrandProfitabilityRoute
  AuthenticatedErpFinanceBudgetsRoute: typeof AuthenticatedErpFinanceBudgetsRoute
  AuthenticatedErpFinanceFxRoute: typeof AuthenticatedErpFinanceFxRoute
  AuthenticatedErpFinanceJournalRoute: typeof AuthenticatedErpFinanceJournalRoute
  AuthenticatedErpFinancePayablesRoute: typeof AuthenticatedErpFinancePayablesRoute
  AuthenticatedErpFinanceProductProfitabilityRoute: typeof AuthenticatedErpFinanceProductProfitabilityRoute
  AuthenticatedErpFinanceReceivablesRoute: typeof AuthenticatedErpFinanceReceivablesRoute
  AuthenticatedErpFinanceReconciliationRoute: typeof AuthenticatedErpFinanceReconciliationRoute
  AuthenticatedErpFinanceRecurringRoute: typeof AuthenticatedErpFinanceRecurringRoute
  AuthenticatedErpFinanceReportsRoute: typeof AuthenticatedErpFinanceReportsRoute
  AuthenticatedErpFinanceSettingsRoute: typeof AuthenticatedErpFinanceSettingsRoute
  AuthenticatedErpFinanceSimpleRoute: typeof AuthenticatedErpFinanceSimpleRoute
  AuthenticatedErpFinanceTaxesRoute: typeof AuthenticatedErpFinanceTaxesRoute
  AuthenticatedErpFinanceWalletsRoute: typeof AuthenticatedErpFinanceWalletsRoute
  AuthenticatedErpFinanceIndexRoute: typeof AuthenticatedErpFinanceIndexRoute
}

const AuthenticatedErpFinanceRouteChildren: AuthenticatedErpFinanceRouteChildren =
  {
    AuthenticatedErpFinanceAccountsRoute: AuthenticatedErpFinanceAccountsRoute,
    AuthenticatedErpFinanceAuditRoute: AuthenticatedErpFinanceAuditRoute,
    AuthenticatedErpFinanceBrandProfitabilityRoute:
      AuthenticatedErpFinanceBrandProfitabilityRoute,
    AuthenticatedErpFinanceBudgetsRoute: AuthenticatedErpFinanceBudgetsRoute,
    AuthenticatedErpFinanceFxRoute: AuthenticatedErpFinanceFxRoute,
    AuthenticatedErpFinanceJournalRoute: AuthenticatedErpFinanceJournalRoute,
    AuthenticatedErpFinancePayablesRoute: AuthenticatedErpFinancePayablesRoute,
    AuthenticatedErpFinanceProductProfitabilityRoute:
      AuthenticatedErpFinanceProductProfitabilityRoute,
    AuthenticatedErpFinanceReceivablesRoute:
      AuthenticatedErpFinanceReceivablesRoute,
    AuthenticatedErpFinanceReconciliationRoute:
      AuthenticatedErpFinanceReconciliationRoute,
    AuthenticatedErpFinanceRecurringRoute:
      AuthenticatedErpFinanceRecurringRoute,
    AuthenticatedErpFinanceReportsRoute: AuthenticatedErpFinanceReportsRoute,
    AuthenticatedErpFinanceSettingsRoute: AuthenticatedErpFinanceSettingsRoute,
    AuthenticatedErpFinanceSimpleRoute: AuthenticatedErpFinanceSimpleRoute,
    AuthenticatedErpFinanceTaxesRoute: AuthenticatedErpFinanceTaxesRoute,
    AuthenticatedErpFinanceWalletsRoute: AuthenticatedErpFinanceWalletsRoute,
    AuthenticatedErpFinanceIndexRoute: AuthenticatedErpFinanceIndexRoute,
  }

const AuthenticatedErpFinanceRouteWithChildren =
  AuthenticatedErpFinanceRoute._addFileChildren(
    AuthenticatedErpFinanceRouteChildren,
  )

interface AuthenticatedErpMarketingRouteChildren {
  AuthenticatedErpMarketingAccountingRoute: typeof AuthenticatedErpMarketingAccountingRoute
  AuthenticatedErpMarketingCampaignsRoute: typeof AuthenticatedErpMarketingCampaignsRoute
  AuthenticatedErpMarketingInstallRoute: typeof AuthenticatedErpMarketingInstallRoute
}

const AuthenticatedErpMarketingRouteChildren: AuthenticatedErpMarketingRouteChildren =
  {
    AuthenticatedErpMarketingAccountingRoute:
      AuthenticatedErpMarketingAccountingRoute,
    AuthenticatedErpMarketingCampaignsRoute:
      AuthenticatedErpMarketingCampaignsRoute,
    AuthenticatedErpMarketingInstallRoute:
      AuthenticatedErpMarketingInstallRoute,
  }

const AuthenticatedErpMarketingRouteWithChildren =
  AuthenticatedErpMarketingRoute._addFileChildren(
    AuthenticatedErpMarketingRouteChildren,
  )

interface AuthenticatedErpOrdersRouteChildren {
  AuthenticatedErpOrdersOrderIdRoute: typeof AuthenticatedErpOrdersOrderIdRoute
  AuthenticatedErpOrdersListRoute: typeof AuthenticatedErpOrdersListRoute
  AuthenticatedErpOrdersNewRoute: typeof AuthenticatedErpOrdersNewRoute
  AuthenticatedErpOrdersWebRoute: typeof AuthenticatedErpOrdersWebRoute
  AuthenticatedErpOrdersIndexRoute: typeof AuthenticatedErpOrdersIndexRoute
}

const AuthenticatedErpOrdersRouteChildren: AuthenticatedErpOrdersRouteChildren =
  {
    AuthenticatedErpOrdersOrderIdRoute: AuthenticatedErpOrdersOrderIdRoute,
    AuthenticatedErpOrdersListRoute: AuthenticatedErpOrdersListRoute,
    AuthenticatedErpOrdersNewRoute: AuthenticatedErpOrdersNewRoute,
    AuthenticatedErpOrdersWebRoute: AuthenticatedErpOrdersWebRoute,
    AuthenticatedErpOrdersIndexRoute: AuthenticatedErpOrdersIndexRoute,
  }

const AuthenticatedErpOrdersRouteWithChildren =
  AuthenticatedErpOrdersRoute._addFileChildren(
    AuthenticatedErpOrdersRouteChildren,
  )

interface AuthenticatedErpRouteChildren {
  AuthenticatedErpCourierRoute: typeof AuthenticatedErpCourierRoute
  AuthenticatedErpFinanceRoute: typeof AuthenticatedErpFinanceRouteWithChildren
  AuthenticatedErpInventoryRoute: typeof AuthenticatedErpInventoryRoute
  AuthenticatedErpMarketingRoute: typeof AuthenticatedErpMarketingRouteWithChildren
  AuthenticatedErpOrdersRoute: typeof AuthenticatedErpOrdersRouteWithChildren
  AuthenticatedErpSettingsRoute: typeof AuthenticatedErpSettingsRoute
  AuthenticatedErpSuppliersRoute: typeof AuthenticatedErpSuppliersRoute
  AuthenticatedErpIndexRoute: typeof AuthenticatedErpIndexRoute
}

const AuthenticatedErpRouteChildren: AuthenticatedErpRouteChildren = {
  AuthenticatedErpCourierRoute: AuthenticatedErpCourierRoute,
  AuthenticatedErpFinanceRoute: AuthenticatedErpFinanceRouteWithChildren,
  AuthenticatedErpInventoryRoute: AuthenticatedErpInventoryRoute,
  AuthenticatedErpMarketingRoute: AuthenticatedErpMarketingRouteWithChildren,
  AuthenticatedErpOrdersRoute: AuthenticatedErpOrdersRouteWithChildren,
  AuthenticatedErpSettingsRoute: AuthenticatedErpSettingsRoute,
  AuthenticatedErpSuppliersRoute: AuthenticatedErpSuppliersRoute,
  AuthenticatedErpIndexRoute: AuthenticatedErpIndexRoute,
}

const AuthenticatedErpRouteWithChildren =
  AuthenticatedErpRoute._addFileChildren(AuthenticatedErpRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedErpRoute: typeof AuthenticatedErpRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedErpRoute: AuthenticatedErpRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCronMarketingRebuildRoute: ApiPublicCronMarketingRebuildRoute,
  ApiPublicCronRunRecurringRoute: ApiPublicCronRunRecurringRoute,
  ApiPublicCronSyncCourierRoute: ApiPublicCronSyncCourierRoute,
  ApiPublicCronSyncMarketingRoute: ApiPublicCronSyncMarketingRoute,
  ApiPublicMktTrackRoute: ApiPublicMktTrackRoute,
  ApiPublicMktTrackerDotjsRoute: ApiPublicMktTrackerDotjsRoute,
  ApiPublicWebhookPathaoRoute: ApiPublicWebhookPathaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
