/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedErpRouteImport } from './routes/_authenticated/erp'
import { Route as AuthenticatedErpIndexRouteImport } from './routes/_authenticated/erp.index'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedErpRoute = AuthenticatedErpRouteImport.update({
  id: '/erp',
  path: '/erp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErpIndexRoute = AuthenticatedErpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedErpRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/erp': typeof AuthenticatedErpRouteWithChildren
  '/erp/': typeof AuthenticatedErpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/erp': typeof AuthenticatedErpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/erp': typeof AuthenticatedErpRouteWithChildren
  '/_authenticated/erp/': typeof AuthenticatedErpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/erp' | '/erp/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/erp'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/erp'
    | '/_authenticated/erp/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/erp': {
      id: '/_authenticated/erp'
      path: '/erp'
      fullPath: '/erp'
      preLoaderRoute: typeof AuthenticatedErpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/erp/': {
      id: '/_authenticated/erp/'
      path: '/'
      fullPath: '/erp/'
      preLoaderRoute: typeof AuthenticatedErpIndexRouteImport
      parentRoute: typeof AuthenticatedErpRoute
    }
  }
}

interface AuthenticatedErpRouteChildren {
  AuthenticatedErpIndexRoute: typeof AuthenticatedErpIndexRoute
}

const AuthenticatedErpRouteChildren: AuthenticatedErpRouteChildren = {
  AuthenticatedErpIndexRoute: AuthenticatedErpIndexRoute,
}

const AuthenticatedErpRouteWithChildren =
  AuthenticatedErpRoute._addFileChildren(AuthenticatedErpRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedErpRoute: typeof AuthenticatedErpRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedErpRoute: AuthenticatedErpRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
