/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedErpRouteImport } from './routes/_authenticated/erp'
import { Route as AuthenticatedErpIndexRouteImport } from './routes/_authenticated/erp.index'
import { Route as AuthenticatedErpSuppliersRouteImport } from './routes/_authenticated/erp.suppliers'
import { Route as AuthenticatedErpSettingsRouteImport } from './routes/_authenticated/erp.settings'
import { Route as AuthenticatedErpOrdersRouteImport } from './routes/_authenticated/erp.orders'
import { Route as AuthenticatedErpInventoryRouteImport } from './routes/_authenticated/erp.inventory'
import { Route as AuthenticatedErpFinanceRouteImport } from './routes/_authenticated/erp.finance'
import { Route as AuthenticatedErpCourierRouteImport } from './routes/_authenticated/erp.courier'
import { Route as AuthenticatedErpOrdersIndexRouteImport } from './routes/_authenticated/erp.orders.index'
import { Route as AuthenticatedErpOrdersWebRouteImport } from './routes/_authenticated/erp.orders.web'
import { Route as AuthenticatedErpOrdersNewRouteImport } from './routes/_authenticated/erp.orders.new'
import { Route as AuthenticatedErpOrdersListRouteImport } from './routes/_authenticated/erp.orders.list'
import { Route as AuthenticatedErpOrdersOrderIdRouteImport } from './routes/_authenticated/erp.orders.$orderId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedErpRoute = AuthenticatedErpRouteImport.update({
  id: '/erp',
  path: '/erp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErpIndexRoute = AuthenticatedErpIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedErpRoute,
} as any)
const AuthenticatedErpSuppliersRoute =
  AuthenticatedErpSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedErpRoute,
  } as any)
const AuthenticatedErpSettingsRoute =
  AuthenticatedErpSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedErpRoute,
  } as any)
const AuthenticatedErpOrdersRoute = AuthenticatedErpOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedErpRoute,
} as any)
const AuthenticatedErpInventoryRoute =
  AuthenticatedErpInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedErpRoute,
  } as any)
const AuthenticatedErpFinanceRoute = AuthenticatedErpFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedErpRoute,
} as any)
const AuthenticatedErpCourierRoute = AuthenticatedErpCourierRouteImport.update({
  id: '/courier',
  path: '/courier',
  getParentRoute: () => AuthenticatedErpRoute,
} as any)
const AuthenticatedErpOrdersIndexRoute =
  AuthenticatedErpOrdersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedErpOrdersRoute,
  } as any)
const AuthenticatedErpOrdersWebRoute =
  AuthenticatedErpOrdersWebRouteImport.update({
    id: '/web',
    path: '/web',
    getParentRoute: () => AuthenticatedErpOrdersRoute,
  } as any)
const AuthenticatedErpOrdersNewRoute =
  AuthenticatedErpOrdersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedErpOrdersRoute,
  } as any)
const AuthenticatedErpOrdersListRoute =
  AuthenticatedErpOrdersListRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => AuthenticatedErpOrdersRoute,
  } as any)
const AuthenticatedErpOrdersOrderIdRoute =
  AuthenticatedErpOrdersOrderIdRouteImport.update({
    id: '/$orderId',
    path: '/$orderId',
    getParentRoute: () => AuthenticatedErpOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/erp': typeof AuthenticatedErpRouteWithChildren
  '/erp/courier': typeof AuthenticatedErpCourierRoute
  '/erp/finance': typeof AuthenticatedErpFinanceRoute
  '/erp/inventory': typeof AuthenticatedErpInventoryRoute
  '/erp/orders': typeof AuthenticatedErpOrdersRouteWithChildren
  '/erp/settings': typeof AuthenticatedErpSettingsRoute
  '/erp/suppliers': typeof AuthenticatedErpSuppliersRoute
  '/erp/': typeof AuthenticatedErpIndexRoute
  '/erp/orders/$orderId': typeof AuthenticatedErpOrdersOrderIdRoute
  '/erp/orders/list': typeof AuthenticatedErpOrdersListRoute
  '/erp/orders/new': typeof AuthenticatedErpOrdersNewRoute
  '/erp/orders/web': typeof AuthenticatedErpOrdersWebRoute
  '/erp/orders/': typeof AuthenticatedErpOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/erp/courier': typeof AuthenticatedErpCourierRoute
  '/erp/finance': typeof AuthenticatedErpFinanceRoute
  '/erp/inventory': typeof AuthenticatedErpInventoryRoute
  '/erp/settings': typeof AuthenticatedErpSettingsRoute
  '/erp/suppliers': typeof AuthenticatedErpSuppliersRoute
  '/erp': typeof AuthenticatedErpIndexRoute
  '/erp/orders/$orderId': typeof AuthenticatedErpOrdersOrderIdRoute
  '/erp/orders/list': typeof AuthenticatedErpOrdersListRoute
  '/erp/orders/new': typeof AuthenticatedErpOrdersNewRoute
  '/erp/orders/web': typeof AuthenticatedErpOrdersWebRoute
  '/erp/orders': typeof AuthenticatedErpOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/erp': typeof AuthenticatedErpRouteWithChildren
  '/_authenticated/erp/courier': typeof AuthenticatedErpCourierRoute
  '/_authenticated/erp/finance': typeof AuthenticatedErpFinanceRoute
  '/_authenticated/erp/inventory': typeof AuthenticatedErpInventoryRoute
  '/_authenticated/erp/orders': typeof AuthenticatedErpOrdersRouteWithChildren
  '/_authenticated/erp/settings': typeof AuthenticatedErpSettingsRoute
  '/_authenticated/erp/suppliers': typeof AuthenticatedErpSuppliersRoute
  '/_authenticated/erp/': typeof AuthenticatedErpIndexRoute
  '/_authenticated/erp/orders/$orderId': typeof AuthenticatedErpOrdersOrderIdRoute
  '/_authenticated/erp/orders/list': typeof AuthenticatedErpOrdersListRoute
  '/_authenticated/erp/orders/new': typeof AuthenticatedErpOrdersNewRoute
  '/_authenticated/erp/orders/web': typeof AuthenticatedErpOrdersWebRoute
  '/_authenticated/erp/orders/': typeof AuthenticatedErpOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/erp'
    | '/erp/courier'
    | '/erp/finance'
    | '/erp/inventory'
    | '/erp/orders'
    | '/erp/settings'
    | '/erp/suppliers'
    | '/erp/'
    | '/erp/orders/$orderId'
    | '/erp/orders/list'
    | '/erp/orders/new'
    | '/erp/orders/web'
    | '/erp/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/erp/courier'
    | '/erp/finance'
    | '/erp/inventory'
    | '/erp/settings'
    | '/erp/suppliers'
    | '/erp'
    | '/erp/orders/$orderId'
    | '/erp/orders/list'
    | '/erp/orders/new'
    | '/erp/orders/web'
    | '/erp/orders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/erp'
    | '/_authenticated/erp/courier'
    | '/_authenticated/erp/finance'
    | '/_authenticated/erp/inventory'
    | '/_authenticated/erp/orders'
    | '/_authenticated/erp/settings'
    | '/_authenticated/erp/suppliers'
    | '/_authenticated/erp/'
    | '/_authenticated/erp/orders/$orderId'
    | '/_authenticated/erp/orders/list'
    | '/_authenticated/erp/orders/new'
    | '/_authenticated/erp/orders/web'
    | '/_authenticated/erp/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/erp': {
      id: '/_authenticated/erp'
      path: '/erp'
      fullPath: '/erp'
      preLoaderRoute: typeof AuthenticatedErpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/erp/': {
      id: '/_authenticated/erp/'
      path: '/'
      fullPath: '/erp/'
      preLoaderRoute: typeof AuthenticatedErpIndexRouteImport
      parentRoute: typeof AuthenticatedErpRoute
    }
    '/_authenticated/erp/suppliers': {
      id: '/_authenticated/erp/suppliers'
      path: '/suppliers'
      fullPath: '/erp/suppliers'
      preLoaderRoute: typeof AuthenticatedErpSuppliersRouteImport
      parentRoute: typeof AuthenticatedErpRoute
    }
    '/_authenticated/erp/settings': {
      id: '/_authenticated/erp/settings'
      path: '/settings'
      fullPath: '/erp/settings'
      preLoaderRoute: typeof AuthenticatedErpSettingsRouteImport
      parentRoute: typeof AuthenticatedErpRoute
    }
    '/_authenticated/erp/orders': {
      id: '/_authenticated/erp/orders'
      path: '/orders'
      fullPath: '/erp/orders'
      preLoaderRoute: typeof AuthenticatedErpOrdersRouteImport
      parentRoute: typeof AuthenticatedErpRoute
    }
    '/_authenticated/erp/inventory': {
      id: '/_authenticated/erp/inventory'
      path: '/inventory'
      fullPath: '/erp/inventory'
      preLoaderRoute: typeof AuthenticatedErpInventoryRouteImport
      parentRoute: typeof AuthenticatedErpRoute
    }
    '/_authenticated/erp/finance': {
      id: '/_authenticated/erp/finance'
      path: '/finance'
      fullPath: '/erp/finance'
      preLoaderRoute: typeof AuthenticatedErpFinanceRouteImport
      parentRoute: typeof AuthenticatedErpRoute
    }
    '/_authenticated/erp/courier': {
      id: '/_authenticated/erp/courier'
      path: '/courier'
      fullPath: '/erp/courier'
      preLoaderRoute: typeof AuthenticatedErpCourierRouteImport
      parentRoute: typeof AuthenticatedErpRoute
    }
    '/_authenticated/erp/orders/': {
      id: '/_authenticated/erp/orders/'
      path: '/'
      fullPath: '/erp/orders/'
      preLoaderRoute: typeof AuthenticatedErpOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedErpOrdersRoute
    }
    '/_authenticated/erp/orders/web': {
      id: '/_authenticated/erp/orders/web'
      path: '/web'
      fullPath: '/erp/orders/web'
      preLoaderRoute: typeof AuthenticatedErpOrdersWebRouteImport
      parentRoute: typeof AuthenticatedErpOrdersRoute
    }
    '/_authenticated/erp/orders/new': {
      id: '/_authenticated/erp/orders/new'
      path: '/new'
      fullPath: '/erp/orders/new'
      preLoaderRoute: typeof AuthenticatedErpOrdersNewRouteImport
      parentRoute: typeof AuthenticatedErpOrdersRoute
    }
    '/_authenticated/erp/orders/list': {
      id: '/_authenticated/erp/orders/list'
      path: '/list'
      fullPath: '/erp/orders/list'
      preLoaderRoute: typeof AuthenticatedErpOrdersListRouteImport
      parentRoute: typeof AuthenticatedErpOrdersRoute
    }
    '/_authenticated/erp/orders/$orderId': {
      id: '/_authenticated/erp/orders/$orderId'
      path: '/$orderId'
      fullPath: '/erp/orders/$orderId'
      preLoaderRoute: typeof AuthenticatedErpOrdersOrderIdRouteImport
      parentRoute: typeof AuthenticatedErpOrdersRoute
    }
  }
}

interface AuthenticatedErpOrdersRouteChildren {
  AuthenticatedErpOrdersOrderIdRoute: typeof AuthenticatedErpOrdersOrderIdRoute
  AuthenticatedErpOrdersListRoute: typeof AuthenticatedErpOrdersListRoute
  AuthenticatedErpOrdersNewRoute: typeof AuthenticatedErpOrdersNewRoute
  AuthenticatedErpOrdersWebRoute: typeof AuthenticatedErpOrdersWebRoute
  AuthenticatedErpOrdersIndexRoute: typeof AuthenticatedErpOrdersIndexRoute
}

const AuthenticatedErpOrdersRouteChildren: AuthenticatedErpOrdersRouteChildren =
  {
    AuthenticatedErpOrdersOrderIdRoute: AuthenticatedErpOrdersOrderIdRoute,
    AuthenticatedErpOrdersListRoute: AuthenticatedErpOrdersListRoute,
    AuthenticatedErpOrdersNewRoute: AuthenticatedErpOrdersNewRoute,
    AuthenticatedErpOrdersWebRoute: AuthenticatedErpOrdersWebRoute,
    AuthenticatedErpOrdersIndexRoute: AuthenticatedErpOrdersIndexRoute,
  }

const AuthenticatedErpOrdersRouteWithChildren =
  AuthenticatedErpOrdersRoute._addFileChildren(
    AuthenticatedErpOrdersRouteChildren,
  )

interface AuthenticatedErpRouteChildren {
  AuthenticatedErpCourierRoute: typeof AuthenticatedErpCourierRoute
  AuthenticatedErpFinanceRoute: typeof AuthenticatedErpFinanceRoute
  AuthenticatedErpInventoryRoute: typeof AuthenticatedErpInventoryRoute
  AuthenticatedErpOrdersRoute: typeof AuthenticatedErpOrdersRouteWithChildren
  AuthenticatedErpSettingsRoute: typeof AuthenticatedErpSettingsRoute
  AuthenticatedErpSuppliersRoute: typeof AuthenticatedErpSuppliersRoute
  AuthenticatedErpIndexRoute: typeof AuthenticatedErpIndexRoute
}

const AuthenticatedErpRouteChildren: AuthenticatedErpRouteChildren = {
  AuthenticatedErpCourierRoute: AuthenticatedErpCourierRoute,
  AuthenticatedErpFinanceRoute: AuthenticatedErpFinanceRoute,
  AuthenticatedErpInventoryRoute: AuthenticatedErpInventoryRoute,
  AuthenticatedErpOrdersRoute: AuthenticatedErpOrdersRouteWithChildren,
  AuthenticatedErpSettingsRoute: AuthenticatedErpSettingsRoute,
  AuthenticatedErpSuppliersRoute: AuthenticatedErpSuppliersRoute,
  AuthenticatedErpIndexRoute: AuthenticatedErpIndexRoute,
}

const AuthenticatedErpRouteWithChildren =
  AuthenticatedErpRoute._addFileChildren(AuthenticatedErpRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedErpRoute: typeof AuthenticatedErpRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedErpRoute: AuthenticatedErpRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
