// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

declare global {
  // Runtime-only secret bridge populated by src/server.ts in the server worker.
  // eslint-disable-next-line no-var
  var __LOVABLE_RUNTIME_ENV__: Record<string, string> | undefined;
}

function getServerEnv(key: string) {
  return globalThis.__LOVABLE_RUNTIME_ENV__?.[key] || process.env[key];
}

function getSupabaseAdminConfig() {
  const SUPABASE_URL = getServerEnv('SUPABASE_URL');
  const SUPABASE_SERVICE_ROLE_KEY =
    getServerEnv('SUPABASE_SERVICE_ROLE_KEY') || getServerEnv('ADMIN_SERVICE_ROLE_KEY');

  return { SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY };
}

export function getSupabaseAdminMissingEnv() {
  const { SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY } = getSupabaseAdminConfig();
  return [
    ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
    ...(!SUPABASE_SERVICE_ROLE_KEY ? ['SUPABASE_SERVICE_ROLE_KEY or ADMIN_SERVICE_ROLE_KEY'] : []),
  ];
}

export function isSupabaseAdminConfigured() {
  return getSupabaseAdminMissingEnv().length === 0;
}

function createSupabaseAdminClient() {
  const { SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY } = getSupabaseAdminConfig();

  if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
    const missing = getSupabaseAdminMissingEnv();
    const message = `Supabase admin client is unavailable. Missing: ${missing.join(', ')}.`;
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;
let _supabaseAdminSignature: string | undefined;

function getSupabaseAdminSignature() {
  const { SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY } = getSupabaseAdminConfig();
  return `${SUPABASE_URL ?? ''}:${SUPABASE_SERVICE_ROLE_KEY ?? ''}`;
}

export function tryGetSupabaseAdmin() {
  if (!isSupabaseAdminConfigured()) return null;
  const signature = getSupabaseAdminSignature();
  if (!_supabaseAdmin || _supabaseAdminSignature !== signature) {
    _supabaseAdmin = createSupabaseAdminClient();
    _supabaseAdminSignature = signature;
  }
  return _supabaseAdmin;
}

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    const signature = getSupabaseAdminSignature();
    if (!_supabaseAdmin || _supabaseAdminSignature !== signature) {
      _supabaseAdmin = createSupabaseAdminClient();
      _supabaseAdminSignature = signature;
    }
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
